// =============================================================================
// AUTO-GENERATED CONFIGURATION — 2026-06-29
// Generated by: node plugins/figma/dom-to-canvas/generate-mapping.mjs
// Sources: discovered-props.json + manual-overrides.json
// =============================================================================

var SGDS_COMPONENT_MAP = {
  "sgds-skeleton": { key: "e637146dfde782038c230e94e2b50905588a32a8", name: "Skeleton" },
  "sgds-divider": { key: "0fa48002f60b73b5c40cc5f9960a0d33fa9aede2", name: "Divider" },
  "sgds-button-fullwidth": { key: "2f7bc66011c005ba56f2a80f400f63875ea3e518", name: "Full width button" },
  "sgds-description-list": { key: "f737ee7ccde2b947ccb0873fbe0373c38968e5e5", name: "Description list" },
  "sgds-drawer": { key: "286077554b9c670410265a4efddc044d2f79c830", name: "Drawer" },
  "sgds-icon-list": { key: "9a32ab706ce2f0a23d974f5d1487d98e551d3b69", name: "Icon list" },
  "sgds-close-button": { key: "dfa571631b0ed13939f6bc803b89d0cb7b866734", name: "Close button" },
  "sgds-alert": { key: "78d35168e3f57033a677c8bce6d5242e1e771ffc", name: "Alert" },
  "sgds-pagination": { key: "9e6f67ae6f0a3d36e74371b7e0121a90617f3437", name: "Pagination" },
  "sgds-select": { key: "76689841e9a0e34127817f173746ff90ad4f6d01", name: "Select" },
  "sgds-toast": { key: "1fba52a6b9e5133c161913561e756e717136329b", name: "Toast" },
  "sgds-dropdown": { key: "8abe77a377974f59945df172f56b462c09d930d2", name: "Dropdown" },
  "sgds-badge": { key: "30f64a9fe1033f49f39d7e77f1b318b0549a852f", name: "Badge" },
  "sgds-combo-box": { key: "402b7c27be729d83b27dc56b20ed4012bb7894b5", name: "Combobox" },
  "sgds-overflow-menu": { key: "4f6abe52cb03aad3e9201d579a1b9a42ee0b2f96", name: "Overflow menu" },
  "sgds-file-upload": { key: "c4be285d559cc8e7d1e5022d6246fbd4afad08dd", name: "File upload" },
  "sgds-sidebar": { key: "f82b74ef96b1fba2824eb1b42773e614d1912b61", name: "Sidebar" },
  "sgds-modal": { key: "b22aedc5141b82416d7943e46a78598d44e4423f", name: "Modal" },
  "sgds-table-of-contents": { key: "71c683805758b4fd9be63158a990cac4f9b1cc08", name: "Table of contents" },
  "sgds-textarea": { key: "8309f3c597191757e791ee07827c6d91462e5312", name: "Text area" },
  "sgds-sidenav": { key: "fe7d7f7bb4bad60bf90236bdefad2d621794aea1", name: "Side navigation" },
  "sgds-footer": { key: "bebf3b1311b700524579ee0c84abed609def47cd", name: "Footer" },
  "sgds-masthead": { key: "18cdf31bb749a24322cc64d6085161d53ed76375", name: "Official Government Banner" },
  "sgds-link": { key: "be078ab26a178669da5e19be495a97951e14f5f4", name: "Link" },
  "sgds-icon-button": { key: "3d6ef97abfa684a4590866cbb603c44b86427f2d", name: "Icon button" },
  "sgds-table": { key: "3e453c92dfce98aa59f3fdf54743848ba1928478", name: "Table" },
  "sgds-datepicker": { key: "22707078ef36a68de4d1d59b52d1e774523b3d9e", name: "Date picker" },
  "sgds-breadcrumb": { key: "0fe6194b637fc81281ba384c7cb7595e36e2aa23", name: "Breadcrumb" },
  "sgds-radio": { key: "529c74d47e2706156c625441dee324962caf32a9", name: "Radio" },
  "sgds-subnav": { key: "f224ffd722edb29ae69e98f57adc236a30e4ab60", name: "Sub nav" },
  "sgds-image-card": { key: "4a9e664f1b163b039023ebeebc3bd2e2f16bb256", name: "Image card" },
  "sgds-progress-bar": { key: "7343e7e18d316aaf3a076f67474c394a69106130", name: "Progress bar" },
  "sgds-checkbox": { key: "cfd682cb134b8cba84738cabe537e7f4973a97af", name: "Checkbox" },
  "sgds-card": { key: "a80a897e32592c4f2d8aebfafffc1d760669b55f", name: "Card" },
  "sgds-button": { key: "6f2f3d88022cd929560600e6d9df2016dd542b3c", name: "Button" },
  "sgds-tab": { key: "84c758d53a47383d98f776a64e12c5e34b3a3042", name: "Tab" },
  "sgds-radio-group": { key: "1bc0266f520ffce648079e4137dedee58896ff57", name: "Radio group" },
  "sgds-switch": { key: "4feb4a7ce800cc003834a757142e2fae22b407cb", name: "Switch" },
  "sgds-spinner": { key: "57f93a97c6752fe191c5baaae85fcd94af48fb6c", name: "Spinner" },
  "sgds-input": { key: "2ef894eecddfbaad424e24480aaaa70c6232d579", name: "Input" },
  "sgds-quantity-toggle": { key: "7a8181de949074a2d44261aa6d6387381ff7fafd", name: "Quantity toggle" },
  "sgds-stepper": { key: "f2d7340d4a7cae5305c275cdf4536a881006adaa", name: "Stepper" },
  "sgds-checkbox-group": { key: "a8736f77a9aa8db166ba3e6a2af36ea62f231796", name: "Checkbox group" },
  "sgds-accordion": { key: "ffada43a96f710368e420ffd6087b09ee8894502", name: "Accordion" },
  "sgds-thumbnail-card": {
    key: "a80a897e32592c4f2d8aebfafffc1d760669b55f",
    name: "Card",
    nestedProps: { Variant: "thumbnail" }
  },
  "sgds-icon-card": { key: "a80a897e32592c4f2d8aebfafffc1d760669b55f", name: "Card", nestedProps: { Variant: "icon" } }
};

var ATTR_TO_VARIANT_PROP = {
  variant: "Variant",
  orientation: "Orientation",
  thickness: "Thickness",
  tone: "Tone",
  size: "Size",
  state: "State",
  outlined: "Outlined",
  dismissible: "Dismissible",
  density: "Density"
};

var ATTR_VALUE_MAP = {
  true: "True",
  false: "False",
  md: "md (default)",
  "fixed-light": "fixed light (white)",
  "fixed-dark": "fixed dark",
  outline: "outline (secondary)",
  ghost: "ghost (tertiary)",
  thin: "thin (default)"
};

var COMPONENT_SLOT_CONFIG = {
  "sgds-button-fullwidth": {
    textProps: {
      label: {
        key: "Edit button label#12484:5",
        source: "text"
      }
    }
  },
  "sgds-description-list": {
    itemPattern: "List",
    itemProps: {},
    childCountVariant: {
      prop: "No. of lists",
      childTag: "sgds-description-list-item"
    }
  },
  "sgds-drawer": {
    slots: {
      default: {
        booleanKey: "🔷 Slot#25042:9",
        instanceName: ".slot"
      }
    }
  },
  "sgds-icon-list": {
    itemPattern: "Icon list",
    itemProps: {
      label: {
        key: "Edit label#16905:74",
        source: "text"
      },
      data: {
        key: "Edit data#16905:73",
        source: "slot:data"
      }
    },
    childCountVariant: {
      prop: "No. of list",
      childTag: "sgds-icon-list-item"
    }
  },
  "sgds-close-button": {
    valueOverrides: {
      "fixed-light": "fixed light",
      "fixed-dark": "fixed dark"
    }
  },
  "sgds-alert": {
    slots: {
      action: {
        booleanKey: "🔷 Action slot#29246:0",
        instanceName: ".slot"
      }
    },
    textProps: {
      title: {
        key: "↳ Edit text#15588:34",
        booleanKey: "Title#15588:17",
        source: "attr:title"
      },
      description: {
        key: "Edit description#13094:45",
        source: "slot:default"
      }
    }
  },
  "sgds-pagination": {
    textProps: {
      description: {
        key: "Edit description#16740:0",
        source: "text"
      }
    }
  },
  "sgds-select": {
    textProps: {
      label: {
        key: "↳ Edit text #16273:0",
        booleanKey: "Label#16252:5",
        source: "attr:label"
      },
      placeholder: {
        key: "↳ Edit text  #16273:12",
        booleanKey: "Placeholder text#16259:126",
        source: "attr:placeholder"
      },
      hint: {
        key: "↳ Edit text   #16273:36",
        booleanKey: "Hint text#16252:0",
        source: "attr:hintText"
      }
    }
  },
  "sgds-toast": {
    textProps: {
      title: {
        key: "↳ Edit text#16370:284",
        booleanKey: "Title#29198:3",
        source: "attr:title"
      },
      description: {
        key: "Edit message#16370:290",
        source: "slot:default"
      }
    }
  },
  "sgds-dropdown": {
    structureName: "Menu"
  },
  "sgds-badge": {
    textProps: {
      label: {
        key: "Edit label#13032:18",
        source: "text"
      }
    }
  },
  "sgds-combo-box": {
    textProps: {
      label: {
        key: "↳ Edit text #16273:0",
        booleanKey: "Label#16252:5",
        source: "attr:label"
      },
      placeholder: {
        key: "↳ Edit text  #16273:12",
        booleanKey: "Placeholder text#16259:126",
        source: "attr:placeholder"
      },
      hint: {
        key: "↳ Edit text   #16273:36",
        booleanKey: "Hint text#16252:0",
        source: "attr:hintText"
      }
    }
  },
  "sgds-overflow-menu": {
    slots: {
      bottom: {
        booleanKey: "🔷 Slot bottom#28035:74"
      },
      top: {
        booleanKey: "🔷 Slot top#28035:6"
      }
    }
  },
  "sgds-file-upload": {
    textProps: {
      label: {
        key: "↳ Edit text  #29661:1",
        booleanKey: "Label#29661:0",
        source: "attr:label"
      },
      hint: {
        key: "↳ Edit text #29661:2",
        booleanKey: "Hint text#29661:3",
        source: "attr:hintText"
      }
    }
  },
  "sgds-sidebar": {
    itemPattern: ".sidebar-l",
    itemProps: {}
  },
  "sgds-modal": {
    slots: {
      default: {
        booleanKey: "🔷 Slot#28535:105",
        instanceName: "[slot group]"
      }
    }
  },
  "sgds-table-of-contents": {
    textProps: {
      header: {
        key: "Edit header#25146:1",
        source: "text"
      }
    }
  },
  "sgds-textarea": {
    textProps: {
      label: {
        key: "↳ Edit text #16273:0",
        booleanKey: "Label#16252:5",
        source: "attr:label"
      },
      placeholder: {
        key: "↳ Edit text  #16273:12",
        booleanKey: "Placeholder text#16259:126",
        source: "attr:placeholder"
      },
      hint: {
        key: "↳ Edit text   #16273:36",
        booleanKey: "Hint text#16252:0",
        source: "attr:hintText"
      }
    }
  },
  "sgds-sidenav": {
    itemPattern: "Sidenav item",
    itemProps: {},
    childCountVariant: {
      prop: "No. of item",
      childTag: "sgds-sidenav-item"
    }
  },
  "sgds-footer": {
    structureName: "Directory"
  },
  "sgds-masthead": {
    slots: {
      trailingIcon: {
        booleanKey: "Trailing icon#15978:15",
        swapKey: "↳ Select icon #17388:25"
      },
      leadingIcon: {
        booleanKey: "Leading icon#15978:6",
        swapKey: "↳ Select icon#17388:0"
      }
    },
    textProps: {
      label: {
        key: "Edit link#16010:0",
        source: "text"
      }
    }
  },
  "sgds-link": {
    slots: {
      leadingIcon: {
        booleanKey: "Leading icon#15978:6",
        swapKey: "↳ Select icon#17388:0"
      },
      trailingIcon: {
        booleanKey: "Trailing icon#15978:15",
        swapKey: "↳ Select icon #17388:25"
      }
    },
    textProps: {
      label: {
        key: "Edit link#16010:0",
        source: "text"
      }
    },
    valueOverrides: {
      "fixed-dark": "fixed dark (black)"
    }
  },
  "sgds-icon-button": {
    slots: {
      icon: {
        swapKey: "Select icon#17388:218"
      }
    }
  },
  "sgds-datepicker": {
    textProps: {
      label: {
        key: "↳ Edit text #16273:0",
        booleanKey: "Label#16252:5",
        source: "attr:label"
      },
      hint: {
        key: "↳ Edit text   #16273:36",
        booleanKey: "Hint text#16252:0",
        source: "attr:hintText"
      }
    }
  },
  "sgds-breadcrumb": {
    itemPattern: "Breadcrumb",
    itemProps: {
      label: {
        key: "Edit link#16129:0"
      },
      state: {
        prop: "State",
        activeValue: "active",
        defaultValue: "default"
      }
    },
    childCountVariant: {
      prop: "No. of link",
      childTag: "sgds-breadcrumb-item"
    }
  },
  "sgds-radio": {
    textProps: {
      label: {
        key: "↳ Edit text#15163:0",
        booleanKey: "Label#16008:16",
        source: "text"
      }
    }
  },
  "sgds-subnav": {
    slots: {
      leadingIcon: {
        booleanKey: "Leading icon#12484:3",
        swapKey: "↳ Select icon#16370:0"
      },
      trailingIcon: {
        booleanKey: "Trailing icon#12484:1",
        swapKey: "↳ Select icon #16370:162"
      }
    },
    textProps: {
      title: {
        key: "Edit header#27781:3",
        source: "attr:title"
      },
      label: {
        key: "Edit button label#12484:5",
        source: "text"
      }
    },
    itemPattern: "Button",
    itemProps: {
      label: {
        key: "Edit button label#12484:5"
      },
      state: {
        prop: "State",
        activeValue: "active",
        defaultValue: "default"
      }
    }
  },
  "sgds-image-card": {
    attrOverrides: {
      hideBorder: {
        prop: "Border",
        values: {
          true: "False",
          false: "True"
        }
      },
      disabled: {
        prop: "State",
        values: {
          true: "disabled"
        }
      }
    },
    structureName: "Card structure",
    slots: {
      upper: {
        booleanKey: "🔷 Upper slot#29125:13",
        swapKey: "↳ Swap instance (upper)#29125:26"
      },
      lower: {
        booleanKey: "🔷 Lower slot#29125:39",
        swapKey: "↳ Swap instance (lower)#31095:9"
      }
    }
  },
  "sgds-progress-bar": {
    itemPattern: "1",
    itemProps: {}
  },
  "sgds-checkbox": {
    textProps: {
      label: {
        key: "↳ Edit text#15167:0",
        booleanKey: "Label#16008:0",
        source: "text"
      }
    }
  },
  "sgds-card": {
    attrOverrides: {
      hideBorder: {
        prop: "Border",
        values: {
          true: "False",
          false: "True"
        }
      },
      disabled: {
        prop: "State",
        values: {
          true: "disabled"
        }
      }
    },
    structureName: "Structure",
    slots: {
      upper: {
        booleanKey: "🔷 Upper slot#29055:1",
        swapKey: "↳ Swap instance (upper)#29055:60",
        frameName: "[upper slot]"
      },
      lower: {
        booleanKey: "🔷 Lower slot#29055:12",
        swapKey: "↳ Swap instance (lower)#30708:0",
        frameName: "[lower slot]"
      }
    }
  },
  "sgds-button": {
    slots: {
      leftIcon: {
        booleanKey: "Leading icon#12484:3",
        swapKey: "↳ Select icon#17388:71"
      },
      rightIcon: {
        booleanKey: "Trailing icon#12484:1",
        swapKey: "↳ Select icon #17388:169"
      }
    },
    textProps: {
      label: {
        key: "Edit button label#12484:5",
        source: "text"
      }
    }
  },
  "sgds-radio-group": {
    attrOverrides: {
      invalid: {
        prop: "Invalid",
        values: { true: "True", "": "True" },
        defaultValue: "False"
      }
    },
    textProps: {
      label: {
        key: "↳ Edit text #15655:51",
        booleanKey: "Label#15655:31",
        source: "attr:label"
      },
      hint: {
        key: "↳ Edit text#15655:46",
        booleanKey: "Hint text#15655:41",
        source: "attr:hintText"
      },
      feedback: {
        key: "↳ Edit text  #15956:0",
        source: "attr:invalidfeedback"
      }
    },
    itemPattern: "↳ Option",
    itemProps: {
      label: { key: "↳ Edit text#15163:0" },
      selection: { prop: "Selection", checkedValue: "selected", uncheckedValue: "unselected" }
    },
    childCountVariant: { prop: "No. of option", childTag: "sgds-radio" }
  },
  "sgds-switch": {
    textProps: {
      label: {
        key: "↳ Edit text#16008:27",
        booleanKey: "Label#15380:0",
        source: "text"
      }
    }
  },
  "sgds-spinner": {
    textProps: {
      label: {
        key: "↳ Edit text#26271:0",
        booleanKey: "Label#16158:6",
        source: "text"
      }
    }
  },
  "sgds-input": {
    slots: {
      icon: {
        swapKey: "↳ Select icon#16259:56"
      }
    },
    textProps: {
      label: {
        key: "↳ Edit text #16273:0",
        booleanKey: "Label#16252:5",
        source: "attr:label"
      },
      placeholder: {
        key: "↳ Edit text  #16273:12",
        booleanKey: "Placeholder text#16259:126",
        source: "attr:placeholder"
      },
      hint: {
        key: "↳ Edit text   #16273:36",
        booleanKey: "Hint text#16252:0",
        source: "attr:hintText"
      }
    }
  },
  "sgds-quantity-toggle": {
    textProps: {
      label: {
        key: "↳ Edit text#16461:94",
        booleanKey: "Label#16461:83",
        source: "attr:label"
      },
      hint: {
        key: "↳ Edit text    #16461:149",
        booleanKey: "Hint text#16461:66",
        source: "attr:hintText"
      }
    }
  },
  "sgds-stepper": {
    itemPattern: "↳ Step",
    itemProps: {
      label: {
        key: "Edit title#16551:8",
        source: "slot:default"
      }
    },
    childCountVariant: {
      prop: "No. of step",
      childTag: "sgds-stepper-item"
    }
  },
  "sgds-checkbox-group": {
    attrOverrides: {
      invalid: {
        prop: "Invalid",
        values: { true: "True", "": "True" },
        defaultValue: "False"
      }
    },
    textProps: {
      label: {
        key: "↳ Edit text  #15640:6",
        booleanKey: "Label#15640:9",
        source: "attr:label"
      },
      hint: {
        key: "↳ Edit text #15640:7",
        booleanKey: "Hint text#15640:8",
        source: "attr:hintText"
      },
      feedback: {
        key: "↳ Edit text#15868:37",
        source: "attr:invalidfeedback"
      }
    },
    itemPattern: "↳ Option",
    itemProps: {
      label: { key: "↳ Edit text#15167:0" },
      selection: { prop: "Selection", checkedValue: "selected", uncheckedValue: "unselected" }
    },
    childCountVariant: { prop: "No. of option", childTag: "sgds-checkbox" }
  },
  "sgds-accordion": {
    attrOverrides: {
      variant: {
        prop: "Border",
        values: {
          border: "True",
          default: "False"
        }
      }
    },
    itemPattern: "↳ Accordion",
    itemProps: {
      title: {
        key: "Edit title#16551:8",
        source: "slot:header"
      },
      badge: {
        booleanKey: "Badge#29585:8",
        swapKey: "↳ 🔷 Swap instance#16545:8"
      },
      icon: {
        booleanKey: "Icon#29595:24",
        swapKey: "↳ Select icon#29595:46"
      },
      disabled: {
        variantProp: "State",
        variantValue: "disabled"
      },
      open: {
        variantProp: "Expand",
        variantValue: "True"
      }
    },
    childCountVariant: {
      prop: "No. of item",
      childTag: "sgds-accordion-item"
    }
  }
};

// =============================================================================
// FIGMA PROPERTY REFERENCE (from discovered-props.json)
// Use this to understand what's available for each component
// =============================================================================

// --- sgds-skeleton (Skeleton) ---
//   Variants:
//     Variant: circle, rectangle, square, text
//   Booleans:
//     "row 2#18098:0" (default: true)
//     "row 3#18098:6" (default: true)
//     "row 4#18098:12" (default: false)
//     "row 5#18098:18" (default: false)
//
// --- sgds-divider (Divider) ---
//   Variants:
//     Orientation: horizontal, vertical
//     Thickness: thick, thicker, thin (default)
//
// --- sgds-button-fullwidth (Full width button) ---
//   Variants:
//     Variant: ghost (tertiary), outlined (secondary), primary
//     Tone: brand, danger, fixed light (white), neutral
//     Size: lg, md (default), sm, xs
//     State: default, disabled, focus, hover/active, loading
//     Icon: leading, trailing, without
//   Text:
//     "Edit button label#12484:5" (default: "Button label")
//   Instance Swaps:
//     "↳ Select icon#16370:0"
//     "↳ Select icon #16370:162"
//   Nested instances: Sub component / spinner only, leading-icon, trailing-icon
//
// --- sgds-description-list (Description list) ---
//   Variants:
//     No. of lists: 1, 10, 2, 3, 4, 5, 6, 7, 8, 9
//     Border: False, True
//     Stack data: False, True
//   Booleans:
//     "Header#18907:12" (default: false)
//   Nested instances: Header, List 1, List 2, List 3, List 4, List 5, List 6, List 7, List 8, List 9, List 10
//   Item patterns: "List" (x220)
//
// --- sgds-drawer (Drawer) ---
//   Variants:
//     Size: large, medium, small (default)
//     Mobile: False, True
//   Booleans:
//     "🔷 Slot#25042:9" (default: true)
//     "Header#25042:10" (default: true)
//     "Scrollbar#25042:12" (default: true)
//     "Scrim background#30108:0" (default: true)
//     "Description#30108:5" (default: true)
//     "Footer#30108:10" (default: true)
//   Text:
//     "Edit title#25042:11" (default: "Title")
//     "↳ Edit text#25042:13" (default: "Description")
//   Instance Swaps:
//     "↳ Swap instance#29538:27"
//   Nested instances: .slot, Close button, Button group
//
// --- sgds-icon-list (Icon list) ---
//   Variants:
//     No. of list: 1, 2, 3, 4, 5, 6, 7, 8
//     Size: lg, md (default), sm
//   Nested instances: Icon list 1, Icon list 2, Icon list 3, Icon list 4, Icon list 5, Icon list 6, Icon list 7, Icon list 8
//   Item patterns: "Icon list" (x108)
//
// --- sgds-close-button (Close button) ---
//   Variants:
//     Variant: default, fixed dark, fixed light
//     Size: md, sm
//     State: default, focus, hover
//   Nested instances: cross
//
// --- sgds-alert (Alert) ---
//   Variants:
//     Variant: danger, info, neutral, success, warning
//     Outlined: False, True
//   Booleans:
//     "With icon#13094:43" (default: true)
//     "Dismissible#13094:44" (default: true)
//     "Title#15588:17" (default: true)
//     "🔷 Action slot#29246:0" (default: false)
//   Text:
//     "Edit description#13094:45" (default: "Description with")
//     "↳ Edit text#15588:34" (default: "Title")
//   Instance Swaps:
//     "↳ Swap instance#29246:11"
//   Nested instances: icon, .slot, Close button
//
// --- sgds-pagination (Pagination) ---
//   Variants:
//     Variant: button only, default, description
//     Size: md (default), sm
//     7 pages or less: False, True
//     Navigation type: Button, Icon button
//   Booleans:
//     "Navigation #24393:38" (default: true)
//   Text:
//     "Edit description#16740:0" (default: "Page 1 of 20")
//   Nested instances: Previous, Pages, Next
//
// --- sgds-select (Select) ---
//   Variants:
//     State: active, default, disabled, empty, focus, hover, invalid, loading, read-only
//     Filled: False, True
//   Booleans:
//     "Hint text#16252:0" (default: false)
//     "Label#16252:5" (default: true)
//     "Placeholder text#16259:126" (default: true)
//     "Action#29548:77" (default: false)
//   Text:
//     "↳ Edit text #16273:0" (default: "Label")
//     "↳ Edit text  #16273:12" (default: "Select an option")
//     "↳ Edit text#16273:24" (default: "Option label")
//     "↳ Edit text   #16273:36" (default: "Hint text")
//     "Edit feedback  #16273:48" (default: "Feedback")
//   Nested instances: Icon button, trailing-icon, exclamation-circle-fill, Menu
//
// --- sgds-toast (Toast) ---
//   Variants:
//     Variant: danger, info, neutral, success, warning
//   Booleans:
//     "Action#16370:296" (default: true)
//     "Dismissable#16370:302" (default: true)
//     "Title#29198:3" (default: true)
//   Text:
//     "↳ Edit text#16370:284" (default: "Title")
//     "Edit message#16370:290" (default: "Message")
//   Nested instances: icon, Link, Close button
//
// --- sgds-dropdown (Dropdown) ---
//   Variants:
//     Trigger: button, icon button
//     Menu position: bottom left, bottom right, top left, top right
//   Nested instances: Icon button, Menu, Button
//
// --- sgds-badge (Badge) ---
//   Variants:
//     Variant: accent, cyan, danger, neutral, primary, purple, success, warning, white
//     Outlined: False, True
//     Dismissible: False, True
//   Booleans:
//     "Icon#13032:36" (default: false)
//   Text:
//     "Edit label#13032:18" (default: "Badge label")
//   Instance Swaps:
//     "↳ Select icon#17388:50"
//   Nested instances: leading-icon, Close button
//
// --- sgds-combo-box (Combobox) ---
//   Variants:
//     State: default, disabled, empty, focus, hover, invalid, loading, read-only
//     Multiselect: False, True
//     Expand: False, True
//     Filled: False, True
//   Booleans:
//     "Hint text#16252:0" (default: false)
//     "Label#16252:5" (default: true)
//     "Placeholder text#16259:126" (default: true)
//     "Action#29543:30" (default: false)
//   Text:
//     "↳ Edit text #16273:0" (default: "Label")
//     "↳ Edit text  #16273:12" (default: "Placeholder text")
//     "↳ Edit text#16273:24" (default: "Filled text")
//     "↳ Edit text   #16273:36" (default: "Hint text")
//     "Edit feedback  #16273:48" (default: "Feedback")
//   Nested instances: Icon button, trailing-icon, Badge group, exclamation-circle-fill, Menu
//
// --- sgds-overflow-menu (Overflow menu) ---
//   Variants:
//     Size: md, sm
//     State: active, default, focus, hover
//   Nested instances: three-dots, ↳ Menu
//
// --- sgds-file-upload (File upload) ---
//   Variants:
//     Variant: default, drag and drop
//   Booleans:
//     "Label#29661:0" (default: true)
//     "Hint text#29661:3" (default: true)
//     "Files#29661:8" (default: false)
//   Text:
//     "↳ Edit text  #29661:1" (default: "Label")
//     "↳ Edit text #29661:2" (default: "Hint text")
//   Nested instances: Button, Sub component / Files, Sub component / Drag and drop
//
// --- sgds-sidebar (Sidebar) ---
//   Variants:
//     Collapse: False, True
//     Variant: collapsible, overlay, persistent
//   Booleans:
//     "Upper slot#34629:1" (default: true)
//     "Lower slot#34629:2" (default: false)
//     "Level 2#34629:5" (default: false)
//     "Scrim#35946:4" (default: false)
//   Instance Swaps:
//     "↳ Swap instance#34629:3"
//     "↳ Swap instance #35957:24"
//   Nested instances: .slot, Icon button, Menus [slot], .sidebar-l2
//   Item patterns: ".sidebar-l" (x6)
//
// --- sgds-modal (Modal) ---
//   Variants:
//     Size: lg, md (default), sm, xl
//     Mobile: False, True
//   Booleans:
//     "Header#28535:70" (default: true)
//     "Description#28535:80" (default: true)
//     "Footer#28535:90" (default: true)
//     "↳ Action 1#28535:95" (default: true)
//     "↳ Action 2#28535:100" (default: true)
//     "🔷 Slot#28535:105" (default: true)
//     "Dismissible#28535:110" (default: true)
//     "Scrim#29956:0" (default: false)
//   Text:
//     "Edit title#28535:75" (default: "Modal title")
//     "↳ Edit text #28535:85" (default: "Modal description")
//   Nested instances: [slot group], Action 1, Action 2, Close button
//   Item patterns: "Action" (x10)
//
// --- sgds-table-of-contents (Table of contents) ---
//   Variants:
//     No. of link: 1, 10, 2, 3, 4, 5 (default), 6, 7, 8, 9
//   Text:
//     "Edit header#25146:1" (default: "Header")
//   Nested instances: Link 1, Link 2, Link 3, Link 4, Link 5, Link 6, Link 7, Link 8, Link 9, Link 10
//   Item patterns: "Link" (x55)
//
// --- sgds-textarea (Text area) ---
//   Variants:
//     State: default, disabled, focus, hover, invalid, read-only
//     Auto resize: False, True
//     Filled: False, True
//   Booleans:
//     "Hint text#16252:0" (default: false)
//     "Label#16252:5" (default: true)
//     "Placeholder text#16259:126" (default: true)
//     "Character count#16276:0" (default: true)
//     "Scrollbar#16454:22" (default: false)
//   Text:
//     "↳ Edit text #16273:0" (default: "Label")
//     "↳ Edit text  #16273:12" (default: "Placeholder text")
//     "↳ Edit text#16273:24" (default: "Filled text")
//     "↳ Edit text   #16273:36" (default: "Hint text")
//     "Edit feedback  #16273:48" (default: "Feedback")
//     "↳ Edit text    #16276:12" (default: "0/000")
//   Nested instances: exclamation-circle-fill
//
// --- sgds-sidenav (Side navigation) ---
//   Variants:
//     No. of item: 1, 10, 2, 3, 4, 5, 6, 7, 8, 9
//     With icon: False, True
//   Nested instances: Main menu - 1, Main menu - 2, Main menu - 3, Main menu - 4, Main menu - 5, Main menu - 6, Main menu - 7, Main menu - 8, Main menu - 9, Main menu - 10
//   Item patterns: "Main menu -" (x110)
//
// --- sgds-footer (Footer) ---
//   Variants:
//     Screen size: 1024 to 1279, 1280 to 1439, 1440 and above, 511 and below, 512 to 767, 768 to 1023
//     hasSidebar: False, True
//   Booleans:
//     "Directory#18383:0" (default: false)
//   Nested instances: Directory, Legal
//
// --- sgds-masthead (Official Government Banner) ---
//   Variants:
//     Mobile: False, True
//     Expand: False, True
//   Nested instances: icon, Link, bank-fill, lock-fill
//
// --- sgds-link (Link) ---
//   Variants:
//     Tone: danger, default, fixed dark (black), fixed light (white), neutral
//     Size: lg, md (default), sm, xs
//     State: default, disabled, focus, hover
//   Booleans:
//     "Leading icon#15978:6" (default: false)
//     "Trailing icon#15978:15" (default: false)
//   Text:
//     "Edit link#16010:0" (default: "Link")
//   Instance Swaps:
//     "↳ Select icon#17388:0"
//     "↳ Select icon #17388:25"
//   Nested instances: leading-icon, trailing-icon
//
// --- sgds-icon-button (Icon button) ---
//   Variants:
//     Variant: ghost (tertiary), outline (secondary), primary
//     Tone: danger, fixed light (white), neutral, primary (brand)
//     Size: lg, md (default), sm, xs
//     State: default, disabled, focus, hover/active, loading
//   Instance Swaps:
//     "Select icon#17388:218"
//   Nested instances: icon, Sub component / spinner only
//
// --- sgds-table (Table) ---
//   Variants:
//     No. of column: 2, 3, 4, 5, 6, 7, 8
//     Header position: both, horizontal, vertical
//   Booleans:
//     "Border#29407:3" (default: true)
//   Nested instances: Header, Table body
//
// --- sgds-datepicker (Date picker) ---
//   Variants:
//     State: active, default, disabled, focus, hover, invalid, read-only
//     Filled: False, True
//     Range: False, True
//   Booleans:
//     "Hint text#16252:0" (default: false)
//     "Label#16252:5" (default: true)
//     "Placeholder text#16259:126" (default: true)
//     "Action#29545:52" (default: false)
//   Text:
//     "↳ Edit text #16273:0" (default: "Label")
//     "Edit start date#16273:24" (default: "DD/MM/YYYY")
//     "↳ Edit text   #16273:36" (default: "Hint text")
//     "Edit feedback  #16273:48" (default: "Feedback")
//     "Edit end date#23134:25" (default: "DD/MM/YYYY")
//   Nested instances: Icon button, exclamation-circle-fill, Calendar
//
// --- sgds-breadcrumb (Breadcrumb) ---
//   Variants:
//     No. of link: 2, 3, 4, 5
//     Overflow: False, True
//   Nested instances: Link 1, seperator, Link 2 (overflow), Link 3, Link 4, Link 5, Link 2
//   Item patterns: "Link" (x18)
//
// --- sgds-radio (Radio) ---
//   Variants:
//     State: default, disabled, focus, hover, invalid
//     Selection: selected, unselected
//   Booleans:
//     "Label#16008:16" (default: true)
//   Text:
//     "↳ Edit text#15163:0" (default: "Option label")
//
// --- sgds-subnav (Sub nav) ---
//   Variants:
//     Screen size: 1024 to 1279, 1280 to 1439, 1440 and above, 511 and below, 512 to 767, 768 to 1023
//     Expand: False, True
//   Booleans:
//     "CTA 1#27781:1" (default: true)
//     "CTA 2#27781:2" (default: false)
//     "CTA 3#28367:3" (default: false)
//   Text:
//     "Edit header#27781:3" (default: "Header")
//   Nested instances: Subnav menu, chevron-down, Button 1, Button 2, Button 3, chevron-up
//   Item patterns: "Button" (x18)
//
// --- sgds-image-card (Image card) ---
//   Variants:
//     State: default, disabled, focus, hover
//     Border: False, True
//     Padding: False, True
//   Booleans:
//     "Tinted #18861:0" (default: false)
//   Nested instances: Card structure
//
// --- sgds-progress-bar (Progress bar) ---
//   Variants:
//     Variant: neutral, primary (default)
//     Progress: 0%, 100%, 25%, 50%, 75%
//   Booleans:
//     "Label#16158:0" (default: true)
//   Nested instances: 25, 50, 75, 100
//   Item patterns: "" (x40)
//
// --- sgds-checkbox (Checkbox) ---
//   Variants:
//     State: default, disabled, focus, hover, invalid
//     Selection: indeterminate, selected, unselected
//   Booleans:
//     "Label#16008:0" (default: true)
//   Text:
//     "↳ Edit text#15167:0" (default: "Option label")
//
// --- sgds-card (Card) ---
//   Variants:
//     State: default, disabled, focus, hover
//     Border: False, True
//     Padding: False, True
//   Booleans:
//     "Tinted#29055:104" (default: false)
//   Nested instances: Structure
//
// --- sgds-button (Button) ---
//   Variants:
//     Variant: ghost (tertiary), outline (secondary), primary
//     Tone: brand, danger, fixed light (white), neutral
//     Size: lg, md (default), sm, xs
//     State: default, disabled, focus, hover/active, loading
//   Booleans:
//     "Trailing icon#12484:1" (default: false)
//     "Leading icon#12484:3" (default: false)
//   Text:
//     "Edit button label#12484:5" (default: "Button label")
//   Instance Swaps:
//     "↳ Select icon#17388:71"
//     "↳ Select icon #17388:169"
//   Nested instances: leading-icon, trailing-icon, Sub component / spinner only
//
// --- sgds-tab (Tab) ---
//   Variants:
//     Variant: solid, underlined
//     Density: compact, default
//     Orientation: horizontal, vertical
//     Leading icon: False, True
//   Nested instances: Tabs group
//
// --- sgds-radio-group (Radio group) ---
//   Variants:
//     No. of option: 2, 3, 4, 5, 6, 7, 8
//     Invalid: False, True
//   Booleans:
//     "Label#15655:31" (default: true)
//     "Hint text#15655:41" (default: false)
//   Text:
//     "↳ Edit text#15655:46" (default: "Hint text")
//     "↳ Edit text #15655:51" (default: "Label")
//     "↳ Edit text  #15956:0" (default: "Feedback")
//   Nested instances: ↳ Option 1, ↳ Option 2, ↳ Option 3, ↳ Option 4, ↳ Option 5, ↳ Option 6, ↳ Option 7, ↳ Option 8, exclamation-circle-fill
//   Item patterns: "↳ Option" (x70)
//
// --- sgds-switch (Switch) ---
//   Variants:
//     Size: lg, md (default), sm
//     State: default, disabled, focus, hover
//     Selection: selected, unselected
//     Label position: left, right (default)
//   Booleans:
//     "Label#15380:0" (default: true)
//     "With icon#16978:0" (default: false)
//   Text:
//     "↳ Edit text#16008:27" (default: "Label")
//
// --- sgds-spinner (Spinner) ---
//   Variants:
//     Orientation: horizontal, vertical
//   Booleans:
//     "Label#16158:6" (default: true)
//   Text:
//     "↳ Edit text#26271:0" (default: "Label")
//   Nested instances: Ring
//
// --- sgds-input (Input) ---
//   Variants:
//     State: default, disabled, focus, hover, invalid, loading, read-only, valid
//     Filled: False, True
//   Booleans:
//     "Hint text#16252:0" (default: false)
//     "Label#16252:5" (default: true)
//     "Placeholder text#16259:126" (default: true)
//     "Prefix#17655:26" (default: false)
//     "Suffix#17655:39" (default: false)
//     "Leading icon#17765:50" (default: false)
//     "Action#28842:0" (default: false)
//     "Password icon#28842:13" (default: false)
//     "Trailing icon#28842:26" (default: false)
//   Text:
//     "↳ Edit text #16273:0" (default: "Label")
//     "↳ Edit text   #16273:12" (default: "Placeholder text")
//     "↳ Edit text#16273:24" (default: "Filled text")
//     "↳ Edit text     #16273:36" (default: "Hint text")
//     "Edit feedback  #16273:48" (default: "Feedback")
//     "↳ Edit text  #16461:0" (default: "Prefix")
//     "↳ Edit text    #16461:33" (default: "Suffix")
//   Instance Swaps:
//     "↳ Select icon#16259:56"
//     "↳ Select icon #28842:39"
//   Nested instances: Icon button, leading-icon, eye-icon, trailing-icon, valid-icon, Sub component / spinner only, exclamation-circle-fill
//
// --- sgds-quantity-toggle (Quantity toggle) ---
//   Variants:
//     State: default, disabled, focus, hover, invalid, read-only
//     Filled: False, True
//   Booleans:
//     "Hint text#16461:66" (default: false)
//     "Label#16461:83" (default: true)
//     "Placeholder text#16461:116" (default: true)
//   Text:
//     "Edit feedback  #16461:72" (default: "Feedback")
//     "↳ Edit text#16461:94" (default: "Label")
//     "↳ Edit text #16461:105" (default: "000")
//     "↳ Edit text  #16461:138" (default: "000")
//     "↳ Edit text    #16461:149" (default: "Hint text")
//   Nested instances: Button left, Button right, exclamation-circle-fill
//
// --- sgds-stepper (Stepper) ---
//   Variants:
//     No. of step: 2, 3, 4 (default), 5, 6
//     Variant: icon, number
//     Orientation: horizontal, vertical
//     Clickable: False, True
//   Nested instances: ↳ Step 1, ↳ Step 2, ↳ Step 3, ↳ Step 4, ↳ Step 5, ↳ Step 6
//   Item patterns: "↳ Step" (x160)
//
// --- sgds-checkbox-group (Checkbox group) ---
//   Variants:
//     No. of option: 1, 2, 3, 4, 5, 6, 7, 8
//     Invalid: False, True
//   Booleans:
//     "Hint text#15640:8" (default: false)
//     "Label#15640:9" (default: true)
//   Text:
//     "↳ Edit text  #15640:6" (default: "Label")
//     "↳ Edit text #15640:7" (default: "Hint text")
//     "↳ Edit text#15868:37" (default: "Feedback")
//   Nested instances: ↳ Option 1, ↳ Option 2, ↳ Option 3, ↳ Option 4, ↳ Option 5, ↳ Option 6, ↳ Option 7, ↳ Option 8, exclamation-circle-fill
//   Item patterns: "↳ Option" (x72)
//
// --- sgds-accordion (Accordion) ---
//   Variants:
//     No. of item: 1, 2, 3, 4, 5, 6, 7, 8
//     Density: compact, default, spacious
//     Border: False, True
//   Nested instances: ↳ Accordion 1, ↳ Accordion 2, ↳ Accordion 3, ↳ Accordion 4, ↳ Accordion 5, ↳ Accordion 6, ↳ Accordion 7, ↳ Accordion 8
//   Item patterns: "↳ Accordion" (x216)
//
