import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
const CopyPlugin = require("copy-webpack-plugin")
import "@govtechsg/sgds-web-component/themes/day.css"
import "@govtechsg/sgds-web-component/css/sgds.css"
import ClientSideLibraryLoader from "./components/sgds";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         <ClientSideLibraryLoader/>
      </head>
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
