import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
const CopyPlugin = require("copy-webpack-plugin")

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         <link href='https://cdn.jsdelivr.net/npm/@govtechsg/sgds-web-component@3.5.0/themes/day.css' rel='stylesheet preload' type='text/css' />
         <Script
          type="module"
          id="scoped-element-polyfill"
          src='https://cdn.jsdelivr.net/npm/@webcomponents/scoped-custom-element-registry@0.0.10'
        ></Script>
         <Script
          type="module"
          id="scoped-element-polyfill"
          src="https://cdn.jsdelivr.net/npm/@govtechsg/sgds-web-component@3.5.1"
        ></Script>
      </head>
      <body className={inter.className}>
      {/* <PolyfillContext> */}
        {children}
        {/* </PolyfillContext> */}
        </body>
    </html>
  );
}
