import { html } from "lit";
import { consume } from "@lit/context";
import { property, query, queryAssignedElements } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import genId from "../../utils/generateId";
import dropdownStyle from "../Dropdown/dropdown.css";
import dropdownMenuStyle from "../Dropdown/dropdown-menu.css";
import mainnavDropdownStyle from "./mainnav-dropdown.css";
import SgdsDropdown from "../Dropdown/sgds-dropdown";
import SgdsDropdownItem from "../Dropdown/sgds-dropdown-item";
import SgdsIcon from "../Icon/sgds-icon";
import { MainnavContext } from "./mainnav-context";
import SgdsElement from "../../base/sgds-element";

const TAB = "Tab";
const ENTER = "Enter";
const SPACE = " ";

/**
 * @slot default - The menu items. Pass in sgds-dropdown-item as the menu items
 * @slot toggler - The content of the toggler to pass in html content.
 */
export class SgdsMainnavDropdown extends SgdsElement {
  static styles = [...SgdsElement.styles, dropdownStyle, dropdownMenuStyle, mainnavDropdownStyle];
  static dependencies = {
    "sgds-dropdown": SgdsDropdown,
    "sgds-dropdown-item": SgdsDropdownItem,
    "sgds-icon": SgdsIcon
  };

  @consume({ context: MainnavContext, subscribe: true })
  private _breakpointReached: Boolean;

  /** @internal */
  @query(".nav-link") navLink: HTMLElement;

  /** @internal */
  @query(".dropdown-items") dropdownItems: HTMLElement;

  /** @internal */
  @query(".dropdown-items a") menuHeaderButton: HTMLElement;

  /** @internal */
  @query(".dropdown-items span") menuHeaderText: HTMLElement;

  /** @internal Forwards value to id attribute of toggle button of Dropdown. An unique id generated by default */
  private togglerId: string = genId("dropdown", "button");

  /** When true,  applies active styles on the dropdown button */
  @property({ type: Boolean })
  active = false;

  /** When true,  applies active styles on the dropdown button */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /** @internal */
  @queryAssignedElements({ slot: "toggler" }) private togglerNodes!: HTMLElement[];

  /** @internal */
  @queryAssignedElements() private defaultNodes!: SgdsDropdownItem[];

  /** @internal */
  get defaultSlotItems(): SgdsDropdownItem[] {
    return [...(this.defaultNodes || [])].filter(
      (node: HTMLElement) => typeof node.tagName !== "undefined"
    ) as SgdsDropdownItem[];
  }

  connectedCallback() {
    super.connectedCallback();
    document.addEventListener("close-dropdown-menu", () => {
      this._resetDropdownMenu();
      this._hideDropdownMenuItems();
    });
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    // Clean up the event listener when the element is removed from the DOM
    document.removeEventListener("close-dropdown-menu", () => {
      this._resetDropdownMenu();
      this._hideDropdownMenuItems();
    });
  }

  protected willUpdate(changedProperties: Map<string, unknown>) {
    super.willUpdate(changedProperties);

    if (!this.shadowRoot) {
      return;
    }

    if (this._breakpointReached) {
      this.shadowRoot.adoptedStyleSheets = [dropdownMenuStyle.styleSheet, mainnavDropdownStyle.styleSheet];
    }
  }

  firstUpdated() {
    this.defaultSlotItems.forEach(item => {
      const slottedItem = (item.shadowRoot.querySelector(".dropdown-item slot") as HTMLSlotElement).assignedElements({
        flatten: true
      });

      slottedItem.forEach(item => {
        (item as HTMLElement).tabIndex = -1;
      });
    });
  }

  updated() {
    if (this._breakpointReached) {
      this._adjustNavLink();
      this._copyTextToMenu();
      this._adjustDropdownItem();
      this._resetDropdownMenu();
      this._hideDropdownMenuItems();
    }
  }

  private _handleSlotChange() {
    this.defaultSlotItems.forEach(item => {
      item.addEventListener("keydown", this._handleKeyboardMenuItemsEvent.bind(this));
    });
  }

  private _handleKeyboardMenuItemsEvent(e: KeyboardEvent) {
    const slottedItems = this.defaultSlotItems.filter(item => !item.hasAttribute("disabled"));
    const items = [this.menuHeaderButton, ...slottedItems];
    const itemLength = items.length;
    if (itemLength === 0) {
      return;
    }

    const firstItem = items[0];
    const lastItem = items[itemLength - 1].shadowRoot.querySelector(".nav-link") as HTMLElement;
    let activeElement = document.activeElement as HTMLElement;
    if (activeElement === this) {
      activeElement = this.shadowRoot.activeElement as HTMLElement;
    }

    switch (e.key) {
      case "Tab": {
        if (e.shiftKey) {
          if (activeElement === firstItem) {
            e.preventDefault();
            setTimeout(() => {
              lastItem.focus();
            }, 0);
          }
        } else {
          const activeShadowElement = activeElement.shadowRoot
            ? activeElement.shadowRoot.querySelector(".nav-link")
            : null;
          if (activeShadowElement && activeShadowElement === lastItem) {
            e.preventDefault();
            firstItem.focus();
          }
        }
        break;
      }
      default:
        break;
    }
  }

  private _adjustNavLink() {
    this.navLink.style.minHeight = "auto";
  }

  private _adjustDropdownItem() {
    this.defaultSlotItems.forEach(item => {
      const dropdownItem = item.shadowRoot.querySelector(".dropdown-item") as HTMLElement;
      dropdownItem.classList.add("nav-link");
    });
  }

  private _copyTextToMenu() {
    this.menuHeaderText.innerHTML = this.togglerNodes[0].innerHTML;
  }

  private _hideDropdownMenuItems() {
    this.dropdownItems.style.display = "none";
    this.dropdownItems.setAttribute("aria-hidden", "true");
  }

  private _resetDropdownMenu() {
    const navbarBody = this._getNavbarBody();
    navbarBody.style.removeProperty("transform");
  }

  private _handleKeyboardOpen(event: KeyboardEvent) {
    if (this.disabled) {
      return;
    }

    if (event.key === ENTER || event.key === SPACE) {
      event.preventDefault();
      this._openMenu();
    }
  }

  private _getNavbarBody() {
    const mainNav = document.querySelector("sgds-mainnav") as HTMLElement | null;

    if (!mainNav?.shadowRoot) {
      console.warn("sgds-mainnav or its shadowRoot not found");
      return;
    }

    const navbarBody = mainNav.shadowRoot.querySelector(".navbar-body") as HTMLElement;
    if (!navbarBody) {
      console.warn(".navbar-body not found in sgds-mainnav");
      return;
    }

    return navbarBody;
  }

  private _openMenu() {
    const navbarBody = this._getNavbarBody();
    navbarBody.style.transform = "translateX(-100%)";
    this.dropdownItems.style.removeProperty("display");
    this.dropdownItems.setAttribute("aria-hidden", "false");
    setTimeout(() => {
      this.menuHeaderButton.focus();
    }, 50);
  }

  private _handleHeaderKeyboardEvent(event: KeyboardEvent) {
    switch (event.key) {
      case TAB: {
        this._handleKeyboardMenuItemsEvent(event);
        break;
      }
      case ENTER:
      case SPACE: {
        event.preventDefault();
        this._closeMenu();
        break;
      }
      default:
        break;
    }
  }

  private _closeMenu() {
    // 200ms delay as the transform transition is set to this timing
    this._resetDropdownMenu();
    setTimeout(() => {
      this._hideDropdownMenuItems();
      this.navLink.focus();
    }, 200);
  }

  render() {
    const mobileView = html`
      <a
        class="${classMap({
          "nav-link": true,
          active: this.active,
          disabled: this.disabled
        })}"
        aria-disabled=${this.disabled ? "true" : "false"}
        tabindex=${this.disabled ? "-1" : "0"}
        role="button"
        @click=${this._openMenu}
        @keydown=${this._handleKeyboardOpen}
      >
        <slot name="toggler"></slot>
        <sgds-icon name="chevron-right"></sgds-icon>
      </a>
      <div class="dropdown-items">
        <a tabindex="0" role="button" @click=${this._closeMenu} @keydown=${this._handleHeaderKeyboardEvent}>
          <sgds-icon name="chevron-left"></sgds-icon>
          <span></span>
        </a>
        <slot @slotchange=${this._handleSlotChange}></slot>
      </div>
    `;

    const desktopView = html`<sgds-dropdown
      modifierOpt=${[
        {
          name: "offset",
          options: {
            offset: [0, 0]
          }
        }
      ]}
      ?disabled=${this.disabled}
    >
      <a
        class="${classMap({
          "nav-link": true,
          active: this.active,
          disabled: this.disabled
        })}"
        aria-disabled=${this.disabled ? "true" : "false"}
        id=${this.togglerId}
        tabindex=${this.disabled ? "-1" : "0"}
        role="button"
        slot="toggler"
      >
        <slot name="toggler"></slot>
        <sgds-icon name="chevron-down"></sgds-icon>
      </a>
      <slot></slot>
    </sgds-dropdown>`;

    return this._breakpointReached ? mobileView : desktopView;
  }
}

export default SgdsMainnavDropdown;
